# fly.toml app configuration file generated for pyws-chess on 2024-10-13T11:11:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pyws-chess'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
